# Generated by Django 2.2.3 on 2019-08-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190802_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritething',
            name='audit_log',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_model_name', models.CharField(max_length=50)),
                ('action_performed', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('favorite_thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FavoriteThing')),
            ],
        ),
    ]
