# Generated by Django 2.2.3 on 2019-08-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190806_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='related_model_name',
        ),
    ]
