# Generated by Django 2.2.3 on 2019-08-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_auditlog_related_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritething',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
